version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: dna_325
    restart: unless-stopped
    working_dir: /var/www/dna_325
    tty: true
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./app:/var/www/dna_325
    ports:
      - "9005:9000"
    networks:
      - dna_325

  mysql:
    image: mysql:5.7
    container_name: dna_325_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: dna_325
      MYSQL_USER: dna_325
      MYSQL_PASSWORD: dna_325
      MYSQL_ROOT_PASSWORD: dna_325
    networks:
      - dna_325

  mysql-test:
    image: mysql:5.7
    container_name: dna_325_mysql_test
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33065:3306"
    environment:
      MYSQL_DATABASE: dna_325
      MYSQL_USER: dna_325
      MYSQL_PASSWORD: dna_325
      MYSQL_ROOT_PASSWORD: dna_325
    networks:
      - dna_325

  nginx:
    image: nginx:alpine
    container_name: dna_325_nginx
    restart: unless-stopped
    ports:
      - "8005:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/dna_325
    depends_on:
      - app
    networks:
      - dna_325

  redis:
    image: redis:alpine
    container_name: dna_325_redis
    restart: unless-stopped
    ports:
      - "63795:6379"
    networks:
      - dna_325

  npm:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: dna_325_npm
    restart: unless-stopped
    volumes:
      - ./app:/var/www/dna_325
    networks:
      - dna_325

networks:
  dna_325:
